### ISSUE TITLE
System.Exception: Unable to start Ocelot

### ISSUE THREAD

**Issue by saikiran290695** [catcherwong/Demos#3]
I m new to Ocelot, so i tried to replicate the same code as you did. I added configuration.json file along with changes to be done at startup and program.cs end. 
when i try to run the server, it throws the following error - 
`Unhandled Exception: System.Exception: Unable to start Ocelot, errors are: When not using service discovery DownstreamHostAndPorts must be set and not empty or Ocelot cannot find your service!,When not using service discovery DownstreamHostAndPorts must be set and not empty or Ocelot cannot find your service!
   at Ocelot.Middleware.OcelotMiddlewareExtensions.ThrowToStopOcelotStarting(Response config)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.CreateConfiguration(IApplicationBuilder builder)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder, OcelotPipelineConfiguration pipelineConfiguration)
   at Ocelot.Middleware.OcelotMiddlewareExtensions.UseOcelot(IApplicationBuilder builder)
   at OcelotIntegration.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in D:\OcelotIntegrator\OcelotIntegration\Startup.cs:line 51
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Hosting environment: Development
Content root path: D:\OcelotIntegrator\OcelotIntegration
Now listening on: http://localhost:9000
Application started. Press Ctrl+C to shut down.
`

After this log, server automatically shuts down. 
Any Help on above would be highly appreciated, Thanks

**Comment by catcherwong** [comment]
@saikiran290695 

There are many changes of Ocelot in different version. Based on the error , I **guess** that the version of Ocelot you use is over 3.x, and your configuration may look like this

```JSON
{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/customers",
            "DownstreamScheme": "http",
            "DownstreamHost": "localhost",
            "DownstreamPort": 9001 
        }
    ]
}
```
You need to change the configuration, and make them look like the following

```JSON
{
    "ReRoutes": [
        {
            "DownstreamPathTemplate": "/api/customers",
            "DownstreamScheme": "http",
            "DownstreamHostAndPorts": [
                {
                    "Host": "localhost",
                    "Port": 9001
                }
            ]
        }
    ]
}
```

**Comment by saikiran290695** [comment]
Thanks Its working now :)
